### ISSUE TITLE
Adding audio delay to Awsome TTS 

### ISSUE THREAD

**Issue by increment8964** [Vocab-Apps/anki-awesome-tts#4]
In the old Anki/Awsome TTS there was a tab where you could set a delay before the audio would play. Now I can’t find it. Where did it go? How can I add a delay before the audio plays with on the fly Awsome TTS audio?
![e0912263351217ce0d25dc60a76cd3fb20cf4d23_2_750x1000](https://github.com/user-attachments/assets/297bca64-cd89-4e7a-98b4-c39f4be17006)
![2b8f44d36c5859809a690326b5af70f41b7972cb_2_492x1000](https://github.com/user-attachments/assets/8ff79469-1917-4974-a4da-32ff18b29edd)

**Comment by luc-vocab** [comment]
If you're using an SSML service, you can use the SSML pause tag: https://www.vocab.ai/tutorials/hypertts-tips-and-tricks#add-pauses

**Comment by increment8964** [comment]
The regex rule worked on my macbook, but it doesn't work on my phone on ankidroid. (I tried syncing ofc)😕

**Comment by luc-vocab** [comment]
On the fly TTS will only work on anki desktop. If you want to review on mobile, I recommend you batch generate audio instead.

**Comment by increment8964** [comment]
> On the fly TTS will only work on anki desktop. If you want to review on mobile, I recommend you batch generate audio instead.

I have been using on the fly TTS with no difficulties for weeks on mobile

**Comment by luc-vocab** [comment]
it works, but 1. a different TTS service will be use on mobile (not a service from AwesomeTTS) 2. you won't be able to use text replacement rules, those will only work on desktop Anki.
