### ISSUE TITLE
Problems to add voice add-ons on Awesome TTS

### ISSUE THREAD

**Issue by walbervinicius** [Vocab-Apps/anki-awesome-tts#5]
I came here because I had a problem when I tried to place a voice in a field required for Awesome TTS. I bought the small plan to access the array of voices for Anki and I applied in more than 3.000 cards, and for a while, it worked. When I tried to use HyperTTS and substitute the parameters, I couldn't apply the rules required because nothing was working. Then I did the backup to not lose the previous card configuration, uninstalled HyperTTS, and restarted Anki. Only Awesome TTS was installed because it is easier to handle it, but when I tried to add a new card with new sentences and tried to apply the voice appeared this: 👇🏿

Status code: 403 (b'{"detail": "Authentication credentials were not provided."}')

I don't know what is it, so I asked for help on Anki forums. The only answer that I got there was:  "Have you tried contacting the author of the add-on? Contact the author."

Look, I just wanted to use Anki's voice to hear how the sounds of the sentences are, I just use it for language learning nothing more, so these development stuff aren't my field. I will leave here 2 screenshots of the issues so that you will understand what happened.

![Screenshot_1](https://github.com/user-attachments/assets/32aa91fa-a4b3-4ee2-a7e5-3ba6580b4ad4)
![Screenshot_2](https://github.com/user-attachments/assets/e20ac865-d303-4a9f-8c9f-9997279f4a9e)

**Comment by luc-vocab** [comment]
Hi, can you email me awesometts@airpost.net ? I will need the email you signed up with as well as the API key you're using, but don't publish those on github, instead please send me a private email.

**Comment by luc-vocab** [comment]
Hi, did you already email me ?

**Comment by walbervinicius** [comment]
Yes, I did, right to the email you sent me. What happened, have you not
received it?

**Comment by luc-vocab** [comment]
as discussed over email, the issue should be sorted out.
